#!/usr/bin/env bash
# QB — one-command production deploy (run on the VPS: Ubuntu 22.04/24.04 ARM or x86)
#
# Usage:
#   git clone https://github.com/aleiwi/qb-construction-management.git
#   cd qb-construction-management/deploy
#   ./setup.sh                 # interactive (asks for domain)
#   # or non-interactive:
#   DOMAIN=qb-app.duckdns.org ./setup.sh
#
set -euo pipefail
cd "$(dirname "$0")"

echo "==================================================="
echo "  QB Construction Management — Production Setup"
echo "==================================================="

# ---- 1. Prerequisites -------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "[!] Docker is not installed. Install it first (see DEPLOYMENT.md), then re-run."
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "[!] Docker Compose plugin is missing. Install it first (see DEPLOYMENT.md)."
  exit 1
fi

# ---- 2. Domain --------------------------------------------------------------
DOMAIN="${DOMAIN:-}"
if [ -z "$DOMAIN" ]; then
  read -r -p "Enter your domain (e.g. qb-app.duckdns.org), or press Enter for IP-only HTTP: " DOMAIN || true
  DOMAIN="${DOMAIN:-}"
fi

# ---- 3. Generate .env -------------------------------------------------------
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  echo "[i] $ENV_FILE already exists — reusing. Delete it to regenerate secrets."
else
  echo "[i] Generating $ENV_FILE ..."
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  SECRET_KEY="$(openssl rand -hex 48)"
  FIRST_ADMIN_PASSWORD="$(openssl rand -hex 12)"

  if [ -n "$DOMAIN" ]; then
    SITE_ADDRESS="$DOMAIN"
    SCHEME="https"
    ORIGIN="https://$DOMAIN"
    HOSTS="$DOMAIN,localhost"
    BASE_URL="https://$DOMAIN"
  else
    PUBIP="$(curl -fsS --max-time 10 ifconfig.me 2>/dev/null || echo 'SERVER_IP')"
    SITE_ADDRESS=":80"
    SCHEME="http"
    ORIGIN="http://$PUBIP:80"
    HOSTS="*"
    BASE_URL="http://$PUBIP"
    FORCE_HTTPS="false"   # no TLS terminator here — otherwise the backend would 307 every call to an unreachable https:// URL
    echo "[!] No domain set -> plain HTTP on http://$PUBIP (no HTTPS)."
    echo "    For free HTTPS, create a DuckDNS subdomain and re-run with DOMAIN set."
  fi

  cat > "$ENV_FILE" <<EOF
# QB production env (auto-generated by setup.sh on $(date -u +%FT%TZ))
DOMAIN=${DOMAIN}
SITE_ADDRESS=${SITE_ADDRESS}
SECRET_KEY=${SECRET_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
FIRST_ADMIN_EMAIL=admin@qb.com
FIRST_ADMIN_FULL_NAME=مدير النظام
FIRST_ADMIN_PASSWORD=${FIRST_ADMIN_PASSWORD}
ALLOWED_ORIGINS=${ORIGIN}
TRUSTED_HOSTS=${HOSTS}
FORCE_HTTPS=${FORCE_HTTPS:-true}
FRONTEND_URL=${BASE_URL}
PUBLIC_API_URL=${BASE_URL}
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=QB System <no-reply@qb-system.com>
SMTP_USE_TLS=true
EOF
  chmod 600 "$ENV_FILE"
  echo "[+] $ENV_FILE written (permissions 600)."

  # Persist the generated admin password for the final summary
  ADMIN_PASSWORD_FILE=".admin_password"
  echo "$FIRST_ADMIN_PASSWORD" > "$ADMIN_PASSWORD_FILE"
  chmod 600 "$ADMIN_PASSWORD_FILE"
fi

# ---- 4. Deploy --------------------------------------------------------------
echo "[i] Building and starting the stack (this may take a few minutes on first run)..."
docker compose -f docker-compose.prod.yml up -d --build

echo ""
echo "==================================================="
echo "  Deploy complete"
if [ -n "$DOMAIN" ]; then
  echo "  App URL : https://$DOMAIN"
else
  echo "  App URL : http://$(curl -fsS --max-time 10 ifconfig.me 2>/dev/null || echo 'SERVER_IP')"
fi

# Load admin credentials (generated above, or pre-existing from a prior run)
ADMIN_EMAIL="$(grep '^FIRST_ADMIN_EMAIL=' "$ENV_FILE" | cut -d= -f2-)"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@qb.com}"
if [ -f ".admin_password" ]; then
  ADMIN_PASSWORD="$(cat .admin_password)"
else
  ADMIN_PASSWORD="$(grep '^FIRST_ADMIN_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)"
fi

echo "  Login   : $ADMIN_EMAIL / $ADMIN_PASSWORD"
echo ""
echo "  NEXT STEPS (IMPORTANT):"
echo "  1. Open the app and log in with the admin credentials above."
echo "  2. Change the admin password (or create a personal admin via Users)."
echo "  3. Configure SMTP in .env to enable real emails (verify/reset)."
echo "  4. The first-admin password is also saved in deploy/.admin_password"
echo "     (0600). Delete it after you've stored it in your password manager."
echo "==================================================="